language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly
install:
    - sudo apt-get update
    # - sudo apt-get install php-dev
    - sudo apt-get install php-pear
    - echo ${TRAVIS_PHP_VERSION:0:3}
    - if [ ${TRAVIS_PHP_VERSION:0:3} == "5.4"]; then pecl install uopz-2.0.7; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} == "5.5"]; then pecl install uopz-2.0.7; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} == "5.6"]; then pecl install uopz-2.0.7; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} == "7.0"]; then pecl install uopz; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} == "7.1"]; then pecl install uopz; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} == "7.2"]; then pecl install uopz; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} == "7.3"]; then pecl install uopz; fi
    - echo "extension = uopz.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
   # - cd uopz2
   # - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" ]]; then git checkout PHP5; fi
   # - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then git checkout PHP5; fi
   # - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then git checkout PHP5; fi
   # - phpize
   # - ./configure
   # - make
   # - sudo make install
   # - echo "extension = uopz.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
   # - cd ..
   - php index.php
