language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly
install:
    - sudo apt-get update
script:
    - cd uopz2
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" ]]; then git checkout PHP5; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then git checkout PHP5; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then git checkout PHP5; fi
    - phpize
    - ./configure
    - make
    - echo "extension = uopz.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - cd ..
    - php index.php
