language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly
install:
    - sudo apt-get update
    - sudo apt-get install -y php-pear
script:
    - sudo bash install.sh
    - php index.php
