language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly
install:
    - sudo apt-get update
matrix:
  include:
    - php: 5.4
      env: 'OLDVERSION="5.4"'
    - php: 5.5
      env: 'OLDVERSION="5.5"'
    - php: 5.6
      env: 'OLDVERSION="5.6"'
script:
    - git clone git@github.com:krakjoe/uopz.git
    - cd uopz
    - if [[ -v "${OLDVERSION}" ]]; then git checkout PHP5; fi
    - phpize
    - ./configure
    - make
    - echo "extension = uopz.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - php index.php
